### PR TITLE
Remove minifier code

### PR DESCRIPTION
**Pull request by alexlamsl**
Now expose a new function `lint(input, element)` in addition to `HTMLLint`.

If `element` is omitted then return the lint errors as string (as opposed to `console.log()` previously).

The minor detail being that `html-lint` is already taken on NPM, so @kangax please come up with something 😅

### CODE REVIEW

**Comment by alexlamsl** [comment]
@kangax please turn on Travis CI for this repository 😉

**Comment by kangax** [comment]
My brain is fried, can you remind me how do I do that?

**Comment by alexlamsl** [comment]
@kangax sign in on https://travis-ci.org/kangax/html-lint and the green buttons should lead the way - I've got stuck because I'm not the owner of the project :sweat_smile:

**Comment by alexlamsl** [comment]
In fact it's https://travis-ci.org/profile after signing in

**Comment by kangax** [comment]
Enabled, so try pushing something and it should work

**Comment by alexlamsl** [comment]
@kangax works like a charm - thanks! :+1:

**Comment by kangax** [comment]
No, thanks to you for all the goodness :)

**Comment by alexlamsl** [comment]
CI passed - now we just need to name this project on NPM, as `html-lint` is already taken...

**Comment by kangax** [comment]
One dumb idea is perhaps html-minifier-lint?

**Comment by alexlamsl** [comment]
Sounds logical enough :stuck_out_tongue_closed_eyes:

**Comment by alexlamsl** [comment]
@kangax published to npm, and added you as owner - I've put in as 0.9.0 for now, and I guess once we've done the corresponding removal work on `html-minifer` and verified that it all works we'll publish 1.0.0

**Comment by kangax** [comment]
Perfect, thanks!

**Pull request merged**
